# Generated by Django 3.1.1 on 2021-03-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editdate', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-editdate', '-date'],
            },
        ),
    ]
