
name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:

 flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Ensure latest pip
        run: |
          python -m pip install --upgrade pip wheel

      - name: Install dependencies
        run: |
          python -m pip install tox
      - name: Run linting
        run: |
          python -m pip --version
          python -m tox --version
          python -m tox -e lint

 docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Ensure latest pip
        run: |
          python -m pip install --upgrade pip wheel

      - name: Install dependencies
        run: |
          python -m pip install tox
      - name: Build docs
        run: |
          python -m pip --version
          python -m tox --version
          python -m tox -e docs

 wheel-contents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build check-wheel-contents

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Check wheel contents
        run: |
          # Ignore W004 for Django migrations - they are expected in Django package wheels
          check-wheel-contents --ignore W004 dist/*.whl

 tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade tox tox-py coverage codecov-cli

    - name: Run tox targets for ${{ matrix.python-version }}
      run: |
        tox --py current
        coverage combine
        coverage xml -o coverage.xml

    - name: Coverage reporting
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
